services:
  mysql:
    container_name: mysql
    image: mysql:latest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./mysql_db:/var/lib/mysql
    ports:
      - 3306:3306

        